apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: url-shortener
  labels:
    app: postgres
    managed-by: portainer
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
  database: dXJsc2hvcnRlbmVy

