global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "link-service"
    static_configs:
      - targets: ["link-service:8001"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "redirect-service"
    static_configs:
      - targets: ["redirect-service:8002"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "stats-service"
    static_configs:
      - targets: ["stats-service:8003"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8004"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
