# Link Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-service
  namespace: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: link-service
  template:
    metadata:
      labels:
        app: link-service
    spec:
      containers:
        - name: link-service
          image: itsbaivab/link-service:latest
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: urlshortener
            - name: RABBITMQ_URL
              value: amqp://admin:admin@rabbitmq:5672/
            - name: SERVICE_PORT
              value: "8001"
          ports:
            - containerPort: 8001
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
# Link Service Service
apiVersion: v1
kind: Service
metadata:
  name: link-service
  namespace: url-shortener
spec:
  selector:
    app: link-service
  ports:
    - port: 8001
      targetPort: 8001
