apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: url-shortener-base

# Base resources (no namespace set)
resources:
  - 01-postgres.yaml
  - 03-rabbitmq.yaml
  - 04-link-service.yaml
  - 05-redirect-service.yaml
  - 06-stats-service.yaml
  - 07-notification-service.yaml
  - 08-nginx-gateway.yaml
  - 10-frontend.yaml

configMapGenerator:
  - name: app-config
    literals:
      - DATABASE_HOST=postgres-service
      - DATABASE_PORT=5432
      - DATABASE_NAME=urlshortener
      - DATABASE_USER=postgres
      - RABBITMQ_HOST=rabbitmq-service
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_VHOST=/

# Common labels for all resources
labels:
  - pairs:
      app.kubernetes.io/name: url-shortener
      app.kubernetes.io/version: v1.0.0
      app.kubernetes.io/component: microservice
      app.kubernetes.io/part-of: url-shortener
      app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  description: "URL Shortener Microservices Application"
  maintainer: "url-shortener-team"

# Images to update (useful for CI/CD)
images:
  - name: postgres
    newTag: "15-alpine"
  - name: rabbitmq
    newTag: "3-management"
  - name: itsbaivab/link-service
    newTag: latest
  - name: itsbaivab/redirect-service
    newTag: latest
  - name: itsbaivab/stats-service
    newTag: latest
  - name: itsbaivab/notification-service
    newTag: latest
  - name: itsbaivab/frontend
    newTag: latest

# Secret generator for sensitive data
secretGenerator:
  - name: app-secrets
    literals:
      - DATABASE_PASSWORD=postgres
      - RABBITMQ_PASSWORD=admin
      - SLACK_TOKEN=your-slack-token-here
      - SLACK_CHANNEL_ID=your-slack-channel-id
